// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class AccountNumberDto
    {
        /// <summary>
        /// Initializes a new instance of the AccountNumberDto class.
        /// </summary>
        public AccountNumberDto() { }

        /// <summary>
        /// Initializes a new instance of the AccountNumberDto class.
        /// </summary>
        public AccountNumberDto(string type = default(string), string externalCode1 = default(string), string externalCode2 = default(string), string number = default(string), string description = default(string))
        {
            Type = type;
            ExternalCode1 = externalCode1;
            ExternalCode2 = externalCode2;
            Number = number;
            Description = description;
        }

        /// <summary>
        /// Possible values for this property include: 'Asset', 'Liability',
        /// 'Income', 'Expense'.
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "externalCode1")]
        public string ExternalCode1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "externalCode2")]
        public string ExternalCode2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public string Number { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
