// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class CashSaleUpdateDto
    {
        /// <summary>
        /// Initializes a new instance of the CashSaleUpdateDto class.
        /// </summary>
        public CashSaleUpdateDto() { }

        /// <summary>
        /// Initializes a new instance of the CashSaleUpdateDto class.
        /// </summary>
        public CashSaleUpdateDto(DtoValueString paymentMethodId = default(DtoValueString), DtoValueString creditTermsId = default(DtoValueString), DtoValueString cashAccount = default(DtoValueString), DtoValueString paymentReference = default(DtoValueString), IList<CashSaleLinesUpdateDto> cashSalesLines = default(IList<CashSaleLinesUpdateDto>), DtoValueString referenceNumber = default(DtoValueString), DtoValueString customerNumber = default(DtoValueString), DtoValueDateTime documentDate = default(DtoValueDateTime), DtoValueBoolean hold = default(DtoValueBoolean), DtoValueString postPeriod = default(DtoValueString), DtoValueString financialPeriod = default(DtoValueString), DtoValueString invoiceText = default(DtoValueString), DtoValueString locationId = default(DtoValueString), DtoValueNullableInt32 salesPersonID = default(DtoValueNullableInt32), DtoValueString note = default(DtoValueString))
        {
            PaymentMethodId = paymentMethodId;
            CreditTermsId = creditTermsId;
            CashAccount = cashAccount;
            PaymentReference = paymentReference;
            CashSalesLines = cashSalesLines;
            ReferenceNumber = referenceNumber;
            CustomerNumber = customerNumber;
            DocumentDate = documentDate;
            Hold = hold;
            PostPeriod = postPeriod;
            FinancialPeriod = financialPeriod;
            InvoiceText = invoiceText;
            LocationId = locationId;
            SalesPersonID = salesPersonID;
            Note = note;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paymentMethodId")]
        public DtoValueString PaymentMethodId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "creditTermsId")]
        public DtoValueString CreditTermsId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cashAccount")]
        public DtoValueString CashAccount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paymentReference")]
        public DtoValueString PaymentReference { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cashSalesLines")]
        public IList<CashSaleLinesUpdateDto> CashSalesLines { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "referenceNumber")]
        public DtoValueString ReferenceNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerNumber")]
        public DtoValueString CustomerNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentDate")]
        public DtoValueDateTime DocumentDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hold")]
        public DtoValueBoolean Hold { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postPeriod")]
        public DtoValueString PostPeriod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "financialPeriod")]
        public DtoValueString FinancialPeriod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "invoiceText")]
        public DtoValueString InvoiceText { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locationId")]
        public DtoValueString LocationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "salesPersonID")]
        public DtoValueNullableInt32 SalesPersonID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "note")]
        public DtoValueString Note { get; set; }

    }
}
