// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class ContactInfoUpdateDto
    {
        /// <summary>
        /// Initializes a new instance of the ContactInfoUpdateDto class.
        /// </summary>
        public ContactInfoUpdateDto() { }

        /// <summary>
        /// Initializes a new instance of the ContactInfoUpdateDto class.
        /// </summary>
        public ContactInfoUpdateDto(DtoValueString name = default(DtoValueString), DtoValueString attention = default(DtoValueString), DtoValueString email = default(DtoValueString), DtoValueString web = default(DtoValueString), DtoValueString phone1 = default(DtoValueString), DtoValueString phone2 = default(DtoValueString), DtoValueString fax = default(DtoValueString))
        {
            Name = name;
            Attention = attention;
            Email = email;
            Web = web;
            Phone1 = phone1;
            Phone2 = phone2;
            Fax = fax;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public DtoValueString Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "attention")]
        public DtoValueString Attention { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public DtoValueString Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "web")]
        public DtoValueString Web { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phone1")]
        public DtoValueString Phone1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phone2")]
        public DtoValueString Phone2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fax")]
        public DtoValueString Fax { get; set; }

    }
}
