// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class CreateShipmentActionDto
    {
        /// <summary>
        /// Initializes a new instance of the CreateShipmentActionDto class.
        /// </summary>
        public CreateShipmentActionDto() { }

        /// <summary>
        /// Initializes a new instance of the CreateShipmentActionDto class.
        /// </summary>
        public CreateShipmentActionDto(string orderType = default(string), bool? returnShipmentDto = default(bool?), DateTime? shipmentDate = default(DateTime?), string shipmentWarehouse = default(string))
        {
            OrderType = orderType;
            ReturnShipmentDto = returnShipmentDto;
            ShipmentDate = shipmentDate;
            ShipmentWarehouse = shipmentWarehouse;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderType")]
        public string OrderType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "returnShipmentDto")]
        public bool? ReturnShipmentDto { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipmentDate")]
        public DateTime? ShipmentDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipmentWarehouse")]
        public string ShipmentWarehouse { get; set; }

    }
}
