// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class CustomerNumberDto
    {
        /// <summary>
        /// Initializes a new instance of the CustomerNumberDto class.
        /// </summary>
        public CustomerNumberDto() { }

        /// <summary>
        /// Initializes a new instance of the CustomerNumberDto class.
        /// </summary>
        public CustomerNumberDto(string number = default(string), string name = default(string))
        {
            Number = number;
            Name = name;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public string Number { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
