// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class DtoSegmentUpdate
    {
        /// <summary>
        /// Initializes a new instance of the DtoSegmentUpdate class.
        /// </summary>
        public DtoSegmentUpdate() { }

        /// <summary>
        /// Initializes a new instance of the DtoSegmentUpdate class.
        /// </summary>
        public DtoSegmentUpdate(string dimensionId = default(string), int? segementId = default(int?), DtoValueString description = default(DtoValueString), DtoValueNullableGuid publicId = default(DtoValueNullableGuid), IList<DtoSegmentValueUpdate> segmentValues = default(IList<DtoSegmentValueUpdate>))
        {
            DimensionId = dimensionId;
            SegementId = segementId;
            Description = description;
            PublicId = publicId;
            SegmentValues = segmentValues;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dimensionId")]
        public string DimensionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "segementId")]
        public int? SegementId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public DtoValueString Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "publicId")]
        public DtoValueNullableGuid PublicId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "segmentValues")]
        public IList<DtoSegmentValueUpdate> SegmentValues { get; set; }

    }
}
