// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class DtoSegment
    {
        /// <summary>
        /// Initializes a new instance of the DtoSegment class.
        /// </summary>
        public DtoSegment() { }

        /// <summary>
        /// Initializes a new instance of the DtoSegment class.
        /// </summary>
        public DtoSegment(int? segmentId = default(int?), string description = default(string), int? length = default(int?), string publicId = default(string), string timeStamp = default(string), DateTime? lastModified = default(DateTime?), bool? validate = default(bool?), IList<DtoSegmentValue> segmentValues = default(IList<DtoSegmentValue>))
        {
            SegmentId = segmentId;
            Description = description;
            Length = length;
            PublicId = publicId;
            TimeStamp = timeStamp;
            LastModified = lastModified;
            Validate = validate;
            SegmentValues = segmentValues;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "segmentId")]
        public int? SegmentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "length")]
        public int? Length { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "publicId")]
        public string PublicId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timeStamp")]
        public string TimeStamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastModified")]
        public DateTime? LastModified { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "validate")]
        public bool? Validate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "segmentValues")]
        public IList<DtoSegmentValue> SegmentValues { get; set; }

    }
}
