// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class GeneralLedgerTransactionsQueryParameters
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GeneralLedgerTransactionsQueryParameters class.
        /// </summary>
        public GeneralLedgerTransactionsQueryParameters() { }

        /// <summary>
        /// Initializes a new instance of the
        /// GeneralLedgerTransactionsQueryParameters class.
        /// </summary>
        public GeneralLedgerTransactionsQueryParameters(string branch = default(string), string ledger = default(string), string fromPeriod = default(string), string toPeriod = default(string), string account = default(string), string subaccountId = default(string), string fromDate = default(string), string toDate = default(string), bool? includeUnposted = default(bool?), bool? includeUnreleased = default(bool?), int? skipRecords = default(int?), int? numberToRead = default(int?))
        {
            Branch = branch;
            Ledger = ledger;
            FromPeriod = fromPeriod;
            ToPeriod = toPeriod;
            Account = account;
            SubaccountId = subaccountId;
            FromDate = fromDate;
            ToDate = toDate;
            IncludeUnposted = includeUnposted;
            IncludeUnreleased = includeUnreleased;
            SkipRecords = skipRecords;
            NumberToRead = numberToRead;
        }

        /// <summary>
        /// Mandatory
        /// </summary>
        [JsonProperty(PropertyName = "branch")]
        public string Branch { get; set; }

        /// <summary>
        /// Mandatory
        /// </summary>
        [JsonProperty(PropertyName = "ledger")]
        public string Ledger { get; set; }

        /// <summary>
        /// Mandatory
        /// </summary>
        [JsonProperty(PropertyName = "fromPeriod")]
        public string FromPeriod { get; set; }

        /// <summary>
        /// Mandatory
        /// </summary>
        [JsonProperty(PropertyName = "toPeriod")]
        public string ToPeriod { get; set; }

        /// <summary>
        /// Mandatory
        /// </summary>
        [JsonProperty(PropertyName = "account")]
        public string Account { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subaccountId")]
        public string SubaccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fromDate")]
        public string FromDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "toDate")]
        public string ToDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "includeUnposted")]
        public bool? IncludeUnposted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "includeUnreleased")]
        public bool? IncludeUnreleased { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "skipRecords")]
        public int? SkipRecords { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numberToRead")]
        public int? NumberToRead { get; set; }

    }
}
