// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This class represents a inventory issue in InventoryIssueController.
    /// Used by getting data.
    /// </summary>
    public partial class InventoryIssueUpdateDto
    {
        /// <summary>
        /// Initializes a new instance of the InventoryIssueUpdateDto class.
        /// </summary>
        public InventoryIssueUpdateDto() { }

        /// <summary>
        /// Initializes a new instance of the InventoryIssueUpdateDto class.
        /// </summary>
        public InventoryIssueUpdateDto(DtoValueNullableDecimal controlAmount = default(DtoValueNullableDecimal), IList<InventoryIssueLineUpdateDto> issueLines = default(IList<InventoryIssueLineUpdateDto>), DtoValueString referenceNumber = default(DtoValueString), DtoValueNullableBoolean hold = default(DtoValueNullableBoolean), DtoValueNullableDateTime date = default(DtoValueNullableDateTime), DtoValueString postPeriod = default(DtoValueString), DtoValueString externalReference = default(DtoValueString), DtoValueString description = default(DtoValueString), DtoValueNullableDecimal controlQuantity = default(DtoValueNullableDecimal))
        {
            ControlAmount = controlAmount;
            IssueLines = issueLines;
            ReferenceNumber = referenceNumber;
            Hold = hold;
            Date = date;
            PostPeriod = postPeriod;
            ExternalReference = externalReference;
            Description = description;
            ControlQuantity = controlQuantity;
        }

        /// <summary>
        /// The manually entered summary amount for all specified inventory
        /// items.Â Control AmountÂ is available only if theÂ Validate
        /// Document Totals on EntryÂ option is selected on theÂ Inventory
        /// PreferencesÂ form. If theÂ Control AmountÂ andÂ Total AmountÂ
        /// values do not match, the system generates a warning message and
        /// the issue cannot be saved.
        /// </summary>
        [JsonProperty(PropertyName = "controlAmount")]
        public DtoValueNullableDecimal ControlAmount { get; set; }

        /// <summary>
        /// The inventory issue lines
        /// </summary>
        [JsonProperty(PropertyName = "issueLines")]
        public IList<InventoryIssueLineUpdateDto> IssueLines { get; set; }

        /// <summary>
        /// The unique reference number of the receipt, which the system
        /// automatically assigns according to the numbering sequence
        /// selected for receipts on theÂ Inventory PreferencesÂ IN.10.10.00)
        /// form.
        /// </summary>
        [JsonProperty(PropertyName = "referenceNumber")]
        public DtoValueString ReferenceNumber { get; set; }

        /// <summary>
        /// A check box that you select to give the receipt theÂ On HoldÂ
        /// status. Clear the check box to save the receipt with theÂ
        /// BalancedÂ status.
        /// </summary>
        [JsonProperty(PropertyName = "hold")]
        public DtoValueNullableBoolean Hold { get; set; }

        /// <summary>
        /// The date when the receipt was created. All transactions included
        /// in this document will have this transaction date.
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public DtoValueNullableDateTime Date { get; set; }

        /// <summary>
        /// The financial period to which the transactions recorded in the
        /// document should be posted.
        /// </summary>
        [JsonProperty(PropertyName = "postPeriod")]
        public DtoValueString PostPeriod { get; set; }

        /// <summary>
        /// The external reference number of the inventory issue document (for
        /// example, the vendorâ€™s reference code).
        /// </summary>
        [JsonProperty(PropertyName = "externalReference")]
        public DtoValueString ExternalReference { get; set; }

        /// <summary>
        /// A brief description of the inventory issue or its transactions.
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public DtoValueString Description { get; set; }

        /// <summary>
        /// The manually entered quantity of inventory items.Â Control Qty.Â
        /// is available only if theÂ Validate Document Totals on EntryÂ
        /// option is selected on theÂ Inventory PreferencesÂ form. If theÂ
        /// Control Qty.Â andÂ Total Qty.values do not match, the system
        /// generates a warning message and the issue cannot be saved.
        /// </summary>
        [JsonProperty(PropertyName = "controlQuantity")]
        public DtoValueNullableDecimal ControlQuantity { get; set; }

    }
}
