// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class LedgerDto
    {
        /// <summary>
        /// Initializes a new instance of the LedgerDto class.
        /// </summary>
        public LedgerDto() { }

        /// <summary>
        /// Initializes a new instance of the LedgerDto class.
        /// </summary>
        public LedgerDto(int? internalId = default(int?), string number = default(string), string description = default(string), string balanceType = default(string), string currencyId = default(string), bool? consolidationSource = default(bool?), ConsolBranchDto consolBranch = default(ConsolBranchDto), bool? branchAccounting = default(bool?), DateTime? lastModifiedDateTime = default(DateTime?))
        {
            InternalId = internalId;
            Number = number;
            Description = description;
            BalanceType = balanceType;
            CurrencyId = currencyId;
            ConsolidationSource = consolidationSource;
            ConsolBranch = consolBranch;
            BranchAccounting = branchAccounting;
            LastModifiedDateTime = lastModifiedDateTime;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "internalId")]
        public int? InternalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public string Number { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Possible values for this property include: 'Actual', 'Report',
        /// 'Statistical', 'Budget'.
        /// </summary>
        [JsonProperty(PropertyName = "balanceType")]
        public string BalanceType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currencyId")]
        public string CurrencyId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "consolidationSource")]
        public bool? ConsolidationSource { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "consolBranch")]
        public ConsolBranchDto ConsolBranch { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "branchAccounting")]
        public bool? BranchAccounting { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastModifiedDateTime")]
        public DateTime? LastModifiedDateTime { get; set; }

    }
}
