// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class LocationIdNameDto
    {
        /// <summary>
        /// Initializes a new instance of the LocationIdNameDto class.
        /// </summary>
        public LocationIdNameDto() { }

        /// <summary>
        /// Initializes a new instance of the LocationIdNameDto class.
        /// </summary>
        public LocationIdNameDto(int? id = default(int?), string name = default(string))
        {
            Id = id;
            Name = name;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
