// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class LocationDto
    {
        /// <summary>
        /// Initializes a new instance of the LocationDto class.
        /// </summary>
        public LocationDto() { }

        /// <summary>
        /// Initializes a new instance of the LocationDto class.
        /// </summary>
        public LocationDto(string countryId = default(string), string id = default(string), string name = default(string))
        {
            CountryId = countryId;
            Id = id;
            Name = name;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "countryId")]
        public string CountryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
