// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class PackageDetailLineDto
    {
        /// <summary>
        /// Initializes a new instance of the PackageDetailLineDto class.
        /// </summary>
        public PackageDetailLineDto() { }

        /// <summary>
        /// Initializes a new instance of the PackageDetailLineDto class.
        /// </summary>
        public PackageDetailLineDto(int? lineNumber = default(int?), bool? confirmed = default(bool?), string boxId = default(string), string type = default(string), string description = default(string), double? weight = default(double?), string uom = default(string), double? declaredValue = default(double?), double? codAmount = default(double?), string trackingNumber = default(string), string customRefNbr1 = default(string), string customRefNbr2 = default(string))
        {
            LineNumber = lineNumber;
            Confirmed = confirmed;
            BoxId = boxId;
            Type = type;
            Description = description;
            Weight = weight;
            Uom = uom;
            DeclaredValue = declaredValue;
            CodAmount = codAmount;
            TrackingNumber = trackingNumber;
            CustomRefNbr1 = customRefNbr1;
            CustomRefNbr2 = customRefNbr2;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lineNumber")]
        public int? LineNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "confirmed")]
        public bool? Confirmed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "boxId")]
        public string BoxId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "weight")]
        public double? Weight { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uom")]
        public string Uom { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "declaredValue")]
        public double? DeclaredValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "codAmount")]
        public double? CodAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "trackingNumber")]
        public string TrackingNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customRefNbr1")]
        public string CustomRefNbr1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customRefNbr2")]
        public string CustomRefNbr2 { get; set; }

    }
}
