// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class PaymentLineDto
    {
        /// <summary>
        /// Initializes a new instance of the PaymentLineDto class.
        /// </summary>
        public PaymentLineDto() { }

        /// <summary>
        /// Initializes a new instance of the PaymentLineDto class.
        /// </summary>
        public PaymentLineDto(string documentType = default(string), string refNbr = default(string), double? amountPaid = default(double?), double? cashDiscountTaken = default(double?), double? balanceWriteOff = default(double?), ReasonCodeDto writeOffReasonCode = default(ReasonCodeDto), DateTime? date = default(DateTime?), DateTime? dueDate = default(DateTime?), DateTime? cashDiscountDate = default(DateTime?), double? balance = default(double?), double? cashDiscountBalance = default(double?), string description = default(string), string currency = default(string), string postPeriod = default(string), string customerOrder = default(string), double? crossRate = default(double?))
        {
            DocumentType = documentType;
            RefNbr = refNbr;
            AmountPaid = amountPaid;
            CashDiscountTaken = cashDiscountTaken;
            BalanceWriteOff = balanceWriteOff;
            WriteOffReasonCode = writeOffReasonCode;
            Date = date;
            DueDate = dueDate;
            CashDiscountDate = cashDiscountDate;
            Balance = balance;
            CashDiscountBalance = cashDiscountBalance;
            Description = description;
            Currency = currency;
            PostPeriod = postPeriod;
            CustomerOrder = customerOrder;
            CrossRate = crossRate;
        }

        /// <summary>
        /// Possible values for this property include: 'Invoice', 'DebitNote',
        /// 'CreditNote', 'Payment', 'VoidPayment', 'Prepayment', 'Refund',
        /// 'FinCharge', 'SmallBalanceWo', 'SmallCreditWo', 'CashSale',
        /// 'CashReturn', 'Undefined', 'NoUpdate'.
        /// </summary>
        [JsonProperty(PropertyName = "documentType")]
        public string DocumentType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "refNbr")]
        public string RefNbr { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amountPaid")]
        public double? AmountPaid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cashDiscountTaken")]
        public double? CashDiscountTaken { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "balanceWriteOff")]
        public double? BalanceWriteOff { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "writeOffReasonCode")]
        public ReasonCodeDto WriteOffReasonCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dueDate")]
        public DateTime? DueDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cashDiscountDate")]
        public DateTime? CashDiscountDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "balance")]
        public double? Balance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cashDiscountBalance")]
        public double? CashDiscountBalance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public string Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postPeriod")]
        public string PostPeriod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerOrder")]
        public string CustomerOrder { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crossRate")]
        public double? CrossRate { get; set; }

    }
}
