// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class PaymentLinesUpdateDto
    {
        /// <summary>
        /// Initializes a new instance of the PaymentLinesUpdateDto class.
        /// </summary>
        public PaymentLinesUpdateDto() { }

        /// <summary>
        /// Initializes a new instance of the PaymentLinesUpdateDto class.
        /// </summary>
        public PaymentLinesUpdateDto(string operation = default(string), DtoValueCustomerDocumentTypes documentType = default(DtoValueCustomerDocumentTypes), DtoValueString refNbr = default(DtoValueString), DtoValueDecimal amountPaid = default(DtoValueDecimal), DtoValueDecimal cashDiscountTaken = default(DtoValueDecimal), DtoValueDecimal balanceWriteOff = default(DtoValueDecimal), DtoValueString writeOffReasonCode = default(DtoValueString), DtoValueDecimal crossRate = default(DtoValueDecimal))
        {
            Operation = operation;
            DocumentType = documentType;
            RefNbr = refNbr;
            AmountPaid = amountPaid;
            CashDiscountTaken = cashDiscountTaken;
            BalanceWriteOff = balanceWriteOff;
            WriteOffReasonCode = writeOffReasonCode;
            CrossRate = crossRate;
        }

        /// <summary>
        /// Possible values for this property include: 'Insert', 'Update',
        /// 'Delete'.
        /// </summary>
        [JsonProperty(PropertyName = "operation")]
        public string Operation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentType")]
        public DtoValueCustomerDocumentTypes DocumentType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "refNbr")]
        public DtoValueString RefNbr { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amountPaid")]
        public DtoValueDecimal AmountPaid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cashDiscountTaken")]
        public DtoValueDecimal CashDiscountTaken { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "balanceWriteOff")]
        public DtoValueDecimal BalanceWriteOff { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "writeOffReasonCode")]
        public DtoValueString WriteOffReasonCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crossRate")]
        public DtoValueDecimal CrossRate { get; set; }

    }
}
