// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This class represents a Payment Method in PaymentMethodController.
    /// Used for getting data.
    /// </summary>
    public partial class PaymentMethodDto
    {
        /// <summary>
        /// Initializes a new instance of the PaymentMethodDto class.
        /// </summary>
        public PaymentMethodDto() { }

        /// <summary>
        /// Initializes a new instance of the PaymentMethodDto class.
        /// </summary>
        public PaymentMethodDto(string paymentMethodID = default(string), bool? active = default(bool?), string meansOfPayment = default(string), string description = default(string), bool? useInAP = default(bool?), IList<PaymentMethodDetailDto> details = default(IList<PaymentMethodDetailDto>))
        {
            PaymentMethodID = paymentMethodID;
            Active = active;
            MeansOfPayment = meansOfPayment;
            Description = description;
            UseInAP = useInAP;
            Details = details;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paymentMethodID")]
        public string PaymentMethodID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "active")]
        public bool? Active { get; set; }

        /// <summary>
        /// Possible values for this property include: 'CreditCard',
        /// 'CashOrCheck', 'DirectDeposit'.
        /// </summary>
        [JsonProperty(PropertyName = "meansOfPayment")]
        public string MeansOfPayment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "useInAP")]
        public bool? UseInAP { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "details")]
        public IList<PaymentMethodDetailDto> Details { get; set; }

    }
}
