// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class ShipmentUpdateDto
    {
        /// <summary>
        /// Initializes a new instance of the ShipmentUpdateDto class.
        /// </summary>
        public ShipmentUpdateDto() { }

        /// <summary>
        /// Initializes a new instance of the ShipmentUpdateDto class.
        /// </summary>
        public ShipmentUpdateDto(DtoValueNullableBoolean hold = default(DtoValueNullableBoolean), DtoValueString fromWarehouse = default(DtoValueString), DtoValueString toWarehouse = default(DtoValueString), DtoValueNullableDecimal controlQuantity = default(DtoValueNullableDecimal), DtoValueNullableBoolean overrideContact = default(DtoValueNullableBoolean), DtoValueString businessName = default(DtoValueString), DtoValueString attention = default(DtoValueString), DtoValueString phone1 = default(DtoValueString), DtoValueString email = default(DtoValueString), DtoValueNullableBoolean overrideAddress = default(DtoValueNullableBoolean), DtoValueString addressLine1 = default(DtoValueString), DtoValueString addressLine2 = default(DtoValueString), DtoValueString city = default(DtoValueString), DtoValueString country = default(DtoValueString), DtoValueString county = default(DtoValueString), DtoValueString postalCode = default(DtoValueString), DtoValueString shipVia = default(DtoValueString), DtoValueString fobPoint = default(DtoValueString), DtoValueString shippingTerms = default(DtoValueString), DtoValueString shippingZone = default(DtoValueString), DtoValueNullableBoolean residentialDelivery = default(DtoValueNullableBoolean), DtoValueNullableBoolean saturdayDelivery = default(DtoValueNullableBoolean), DtoValueNullableBoolean useCustomerAccount = default(DtoValueNullableBoolean), DtoValueNullableBoolean insurance = default(DtoValueNullableBoolean), DtoValueNullableDecimal freightAmt = default(DtoValueNullableDecimal), DtoValueNullableInt32 transactionType = default(DtoValueNullableInt32), DtoValueNullableTransportationModes modeOfTrasport = default(DtoValueNullableTransportationModes), DtoValueNullableBoolean container = default(DtoValueNullableBoolean), IList<ShipmentDetailLineUpdateDto> shipmentDetailLines = default(IList<ShipmentDetailLineUpdateDto>), IList<ShipmentPackageLineUpdateDto> shipmentPackageLines = default(IList<ShipmentPackageLineUpdateDto>))
        {
            Hold = hold;
            FromWarehouse = fromWarehouse;
            ToWarehouse = toWarehouse;
            ControlQuantity = controlQuantity;
            OverrideContact = overrideContact;
            BusinessName = businessName;
            Attention = attention;
            Phone1 = phone1;
            Email = email;
            OverrideAddress = overrideAddress;
            AddressLine1 = addressLine1;
            AddressLine2 = addressLine2;
            City = city;
            Country = country;
            County = county;
            PostalCode = postalCode;
            ShipVia = shipVia;
            FobPoint = fobPoint;
            ShippingTerms = shippingTerms;
            ShippingZone = shippingZone;
            ResidentialDelivery = residentialDelivery;
            SaturdayDelivery = saturdayDelivery;
            UseCustomerAccount = useCustomerAccount;
            Insurance = insurance;
            FreightAmt = freightAmt;
            TransactionType = transactionType;
            ModeOfTrasport = modeOfTrasport;
            Container = container;
            ShipmentDetailLines = shipmentDetailLines;
            ShipmentPackageLines = shipmentPackageLines;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hold")]
        public DtoValueNullableBoolean Hold { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fromWarehouse")]
        public DtoValueString FromWarehouse { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "toWarehouse")]
        public DtoValueString ToWarehouse { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "controlQuantity")]
        public DtoValueNullableDecimal ControlQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "overrideContact")]
        public DtoValueNullableBoolean OverrideContact { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "businessName")]
        public DtoValueString BusinessName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "attention")]
        public DtoValueString Attention { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phone1")]
        public DtoValueString Phone1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public DtoValueString Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "overrideAddress")]
        public DtoValueNullableBoolean OverrideAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressLine1")]
        public DtoValueString AddressLine1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressLine2")]
        public DtoValueString AddressLine2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public DtoValueString City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "country")]
        public DtoValueString Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "county")]
        public DtoValueString County { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postalCode")]
        public DtoValueString PostalCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipVia")]
        public DtoValueString ShipVia { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fobPoint")]
        public DtoValueString FobPoint { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shippingTerms")]
        public DtoValueString ShippingTerms { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shippingZone")]
        public DtoValueString ShippingZone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "residentialDelivery")]
        public DtoValueNullableBoolean ResidentialDelivery { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "saturdayDelivery")]
        public DtoValueNullableBoolean SaturdayDelivery { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "useCustomerAccount")]
        public DtoValueNullableBoolean UseCustomerAccount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "insurance")]
        public DtoValueNullableBoolean Insurance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "freightAmt")]
        public DtoValueNullableDecimal FreightAmt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionType")]
        public DtoValueNullableInt32 TransactionType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modeOfTrasport")]
        public DtoValueNullableTransportationModes ModeOfTrasport { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "container")]
        public DtoValueNullableBoolean Container { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipmentDetailLines")]
        public IList<ShipmentDetailLineUpdateDto> ShipmentDetailLines { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipmentPackageLines")]
        public IList<ShipmentPackageLineUpdateDto> ShipmentPackageLines { get; set; }

    }
}
