// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This class represent a Stocktake line in StocktakeContoller. Used to
    /// update a Stocktake line
    /// </summary>
    public partial class StocktakeLineUpdateDto
    {
        /// <summary>
        /// Initializes a new instance of the StocktakeLineUpdateDto class.
        /// </summary>
        public StocktakeLineUpdateDto() { }

        /// <summary>
        /// Initializes a new instance of the StocktakeLineUpdateDto class.
        /// </summary>
        public StocktakeLineUpdateDto(string operation = default(string), DtoValueNullableInt32 lineNbr = default(DtoValueNullableInt32), DtoValueNullableDecimal physicalQuantity = default(DtoValueNullableDecimal))
        {
            Operation = operation;
            LineNbr = lineNbr;
            PhysicalQuantity = physicalQuantity;
        }

        /// <summary>
        /// Possible values for this property include: 'Insert', 'Update',
        /// 'Delete'.
        /// </summary>
        [JsonProperty(PropertyName = "operation")]
        public string Operation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lineNbr")]
        public DtoValueNullableInt32 LineNbr { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "physicalQuantity")]
        public DtoValueNullableDecimal PhysicalQuantity { get; set; }

    }
}
