// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class SupplierDocumentDto
    {
        /// <summary>
        /// Initializes a new instance of the SupplierDocumentDto class.
        /// </summary>
        public SupplierDocumentDto() { }

        /// <summary>
        /// Initializes a new instance of the SupplierDocumentDto class.
        /// </summary>
        public SupplierDocumentDto(AccountNumberDto account = default(AccountNumberDto), SubAccountDto subaccount = default(SubAccountDto), BranchNumberDto branch = default(BranchNumberDto), double? amount = default(double?), double? amountInCurrency = default(double?), SupplierNumberDto supplier = default(SupplierNumberDto), string documentType = default(string), string referenceNumber = default(string), string postPeriod = default(string), string financialPeriod = default(string), DateTime? date = default(DateTime?), DateTime? dueDate = default(DateTime?), string approvalStatus = default(string), string status = default(string), string currencyId = default(string), double? balance = default(double?), double? balanceInCurrency = default(double?), double? cashDiscount = default(double?), double? cashDiscountInCurrency = default(double?), PaymentMethodIdDescriptionDto paymentMethod = default(PaymentMethodIdDescriptionDto), string supplierReference = default(string), string description = default(string), DateTime? createdDateTime = default(DateTime?), DateTime? lastModifiedDateTime = default(DateTime?), string note = default(string), LocationDto location = default(LocationDto), double? vatTotal = default(double?), double? vatTotalInCurrency = default(double?))
        {
            Account = account;
            Subaccount = subaccount;
            Branch = branch;
            Amount = amount;
            AmountInCurrency = amountInCurrency;
            Supplier = supplier;
            DocumentType = documentType;
            ReferenceNumber = referenceNumber;
            PostPeriod = postPeriod;
            FinancialPeriod = financialPeriod;
            Date = date;
            DueDate = dueDate;
            ApprovalStatus = approvalStatus;
            Status = status;
            CurrencyId = currencyId;
            Balance = balance;
            BalanceInCurrency = balanceInCurrency;
            CashDiscount = cashDiscount;
            CashDiscountInCurrency = cashDiscountInCurrency;
            PaymentMethod = paymentMethod;
            SupplierReference = supplierReference;
            Description = description;
            CreatedDateTime = createdDateTime;
            LastModifiedDateTime = lastModifiedDateTime;
            Note = note;
            Location = location;
            VatTotal = vatTotal;
            VatTotalInCurrency = vatTotalInCurrency;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "account")]
        public AccountNumberDto Account { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subaccount")]
        public SubAccountDto Subaccount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "branch")]
        public BranchNumberDto Branch { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amountInCurrency")]
        public double? AmountInCurrency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplier")]
        public SupplierNumberDto Supplier { get; set; }

        /// <summary>
        /// Possible values for this property include: 'Check', 'CreditAdj',
        /// 'DebitAdj', 'Invoice', 'Prepayment', 'QuickCheck', 'Refund',
        /// 'VoidCheck', 'VoidQuickCheck'.
        /// </summary>
        [JsonProperty(PropertyName = "documentType")]
        public string DocumentType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "referenceNumber")]
        public string ReferenceNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postPeriod")]
        public string PostPeriod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "financialPeriod")]
        public string FinancialPeriod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dueDate")]
        public DateTime? DueDate { get; set; }

        /// <summary>
        /// Possible values for this property include: 'New', 'Canceled',
        /// 'SentToApproval', 'ReceivedByApproval', 'InProgressApproval',
        /// 'RejectedInApproval', 'ApprovedInApproval',
        /// 'ActiveWorkflowApproval'.
        /// </summary>
        [JsonProperty(PropertyName = "approvalStatus")]
        public string ApprovalStatus { get; set; }

        /// <summary>
        /// Possible values for this property include: 'Hold', 'Balanced',
        /// 'Voided', 'Scheduled', 'Open', 'Closed', 'Printed', 'Prebooked'.
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currencyId")]
        public string CurrencyId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "balance")]
        public double? Balance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "balanceInCurrency")]
        public double? BalanceInCurrency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cashDiscount")]
        public double? CashDiscount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cashDiscountInCurrency")]
        public double? CashDiscountInCurrency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paymentMethod")]
        public PaymentMethodIdDescriptionDto PaymentMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplierReference")]
        public string SupplierReference { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdDateTime")]
        public DateTime? CreatedDateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastModifiedDateTime")]
        public DateTime? LastModifiedDateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "note")]
        public string Note { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public LocationDto Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vatTotal")]
        public double? VatTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vatTotalInCurrency")]
        public double? VatTotalInCurrency { get; set; }

    }
}
