// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class SupplierPOBalanceDto
    {
        /// <summary>
        /// Initializes a new instance of the SupplierPOBalanceDto class.
        /// </summary>
        public SupplierPOBalanceDto() { }

        /// <summary>
        /// Initializes a new instance of the SupplierPOBalanceDto class.
        /// </summary>
        public SupplierPOBalanceDto(SupplierDescriptionDto supplier = default(SupplierDescriptionDto), double? totalPOOnHoldOrderTotal = default(double?), double? totalPOOnHoldLineTotal = default(double?), double? totalOpenPOOrderTotal = default(double?), double? totalOpenPOLineTotal = default(double?), double? totalClosedPOOrderTotal = default(double?), double? totalClosedPOLineTotal = default(double?), DateTime? lastModifiedDateTime = default(DateTime?))
        {
            Supplier = supplier;
            TotalPOOnHoldOrderTotal = totalPOOnHoldOrderTotal;
            TotalPOOnHoldLineTotal = totalPOOnHoldLineTotal;
            TotalOpenPOOrderTotal = totalOpenPOOrderTotal;
            TotalOpenPOLineTotal = totalOpenPOLineTotal;
            TotalClosedPOOrderTotal = totalClosedPOOrderTotal;
            TotalClosedPOLineTotal = totalClosedPOLineTotal;
            LastModifiedDateTime = lastModifiedDateTime;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplier")]
        public SupplierDescriptionDto Supplier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalPOOnHoldOrderTotal")]
        public double? TotalPOOnHoldOrderTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalPOOnHoldLineTotal")]
        public double? TotalPOOnHoldLineTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalOpenPOOrderTotal")]
        public double? TotalOpenPOOrderTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalOpenPOLineTotal")]
        public double? TotalOpenPOLineTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalClosedPOOrderTotal")]
        public double? TotalClosedPOOrderTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalClosedPOLineTotal")]
        public double? TotalClosedPOLineTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastModifiedDateTime")]
        public DateTime? LastModifiedDateTime { get; set; }

    }
}
