// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class SupplierInvoiceUpdateDto
    {
        /// <summary>
        /// Initializes a new instance of the SupplierInvoiceUpdateDto class.
        /// </summary>
        public SupplierInvoiceUpdateDto() { }

        /// <summary>
        /// Initializes a new instance of the SupplierInvoiceUpdateDto class.
        /// </summary>
        public SupplierInvoiceUpdateDto(DtoValueString referenceNumber = default(DtoValueString), DtoValueBoolean hold = default(DtoValueBoolean), DtoValueDateTime date = default(DtoValueDateTime), DtoValueString postPeriod = default(DtoValueString), DtoValueString financialPeriod = default(DtoValueString), DtoValueString supplierReference = default(DtoValueString), DtoValueString description = default(DtoValueString), DtoValueString supplierNumber = default(DtoValueString), DtoValueString locationId = default(DtoValueString), DtoValueString currencyId = default(DtoValueString), DtoValueString paymentRefNo = default(DtoValueString), DtoValueString creditTermsId = default(DtoValueString), DtoValueDateTime dueDate = default(DtoValueDateTime), DtoValueDateTime cashDiscountDate = default(DtoValueDateTime), DtoValueString note = default(DtoValueString), DtoValueDecimal exchangeRate = default(DtoValueDecimal), IList<SupplierInvoiceLineUpdateDto> invoiceLines = default(IList<SupplierInvoiceLineUpdateDto>))
        {
            ReferenceNumber = referenceNumber;
            Hold = hold;
            Date = date;
            PostPeriod = postPeriod;
            FinancialPeriod = financialPeriod;
            SupplierReference = supplierReference;
            Description = description;
            SupplierNumber = supplierNumber;
            LocationId = locationId;
            CurrencyId = currencyId;
            PaymentRefNo = paymentRefNo;
            CreditTermsId = creditTermsId;
            DueDate = dueDate;
            CashDiscountDate = cashDiscountDate;
            Note = note;
            ExchangeRate = exchangeRate;
            InvoiceLines = invoiceLines;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "referenceNumber")]
        public DtoValueString ReferenceNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hold")]
        public DtoValueBoolean Hold { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public DtoValueDateTime Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postPeriod")]
        public DtoValueString PostPeriod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "financialPeriod")]
        public DtoValueString FinancialPeriod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplierReference")]
        public DtoValueString SupplierReference { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public DtoValueString Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplierNumber")]
        public DtoValueString SupplierNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locationId")]
        public DtoValueString LocationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currencyId")]
        public DtoValueString CurrencyId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paymentRefNo")]
        public DtoValueString PaymentRefNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "creditTermsId")]
        public DtoValueString CreditTermsId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dueDate")]
        public DtoValueDateTime DueDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cashDiscountDate")]
        public DtoValueDateTime CashDiscountDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "note")]
        public DtoValueString Note { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exchangeRate")]
        public DtoValueDecimal ExchangeRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "invoiceLines")]
        public IList<SupplierInvoiceLineUpdateDto> InvoiceLines { get; set; }

    }
}
