// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This class represents a Payment Method Detail in SupplierController.
    /// Used to update SupplierPaymentMethodDetails when creating or updating
    /// a Supplier.
    /// </summary>
    public partial class SupplierPaymentMethodDetailUpdateDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SupplierPaymentMethodDetailUpdateDto class.
        /// </summary>
        public SupplierPaymentMethodDetailUpdateDto() { }

        /// <summary>
        /// Initializes a new instance of the
        /// SupplierPaymentMethodDetailUpdateDto class.
        /// </summary>
        public SupplierPaymentMethodDetailUpdateDto(string paymentMethodDetailDescription = default(string), DtoValueString paymentMethodDetailValue = default(DtoValueString))
        {
            PaymentMethodDetailDescription = paymentMethodDetailDescription;
            PaymentMethodDetailValue = paymentMethodDetailValue;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paymentMethodDetailDescription")]
        public string PaymentMethodDetailDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paymentMethodDetailValue")]
        public DtoValueString PaymentMethodDetailValue { get; set; }

    }
}
