// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class VatCategoryLineDto
    {
        /// <summary>
        /// Initializes a new instance of the VatCategoryLineDto class.
        /// </summary>
        public VatCategoryLineDto() { }

        /// <summary>
        /// Initializes a new instance of the VatCategoryLineDto class.
        /// </summary>
        public VatCategoryLineDto(string vatId = default(string), string description = default(string), string type = default(string), string calculateOn = default(string), string cashDiscount = default(string))
        {
            VatId = vatId;
            Description = description;
            Type = type;
            CalculateOn = calculateOn;
            CashDiscount = cashDiscount;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vatId")]
        public string VatId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Possible values for this property include: 'Sales', 'Use', 'Vat',
        /// 'Withholding', 'ExemptVat', 'StatisticalVat', 'DirectVat',
        /// 'PendingVat', 'ReverseVat'.
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Possible values for this property include:
        /// 'ExtractFromItemAmount', 'ItemAmount', 'ItemTaxAmount',
        /// 'DocumentAmount', 'DocumenTaxAmount'.
        /// </summary>
        [JsonProperty(PropertyName = "calculateOn")]
        public string CalculateOn { get; set; }

        /// <summary>
        /// Possible values for this property include: 'ToTaxableAmount',
        /// 'ToPromtPayment', 'ToTaxAmount', 'AdjustTax', 'NoAdjust'.
        /// </summary>
        [JsonProperty(PropertyName = "cashDiscount")]
        public string CashDiscount { get; set; }

    }
}
