// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class VatGlAccountsDto
    {
        /// <summary>
        /// Initializes a new instance of the VatGlAccountsDto class.
        /// </summary>
        public VatGlAccountsDto() { }

        /// <summary>
        /// Initializes a new instance of the VatGlAccountsDto class.
        /// </summary>
        public VatGlAccountsDto(AccountNumberDto vatPayableAccount = default(AccountNumberDto), SubAccountDescriptionDto vatPayableSubaccount = default(SubAccountDescriptionDto), AccountNumberDto vatClaimableAccount = default(AccountNumberDto), SubAccountDescriptionDto vatClaimableSubccount = default(SubAccountDescriptionDto))
        {
            VatPayableAccount = vatPayableAccount;
            VatPayableSubaccount = vatPayableSubaccount;
            VatClaimableAccount = vatClaimableAccount;
            VatClaimableSubccount = vatClaimableSubccount;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vatPayableAccount")]
        public AccountNumberDto VatPayableAccount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vatPayableSubaccount")]
        public SubAccountDescriptionDto VatPayableSubaccount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vatClaimableAccount")]
        public AccountNumberDto VatClaimableAccount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vatClaimableSubccount")]
        public SubAccountDescriptionDto VatClaimableSubccount { get; set; }

    }
}
