// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace visma.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class VniToken
    {
        /// <summary>
        /// Initializes a new instance of the VniToken class.
        /// </summary>
        public VniToken() { }

        /// <summary>
        /// Initializes a new instance of the VniToken class.
        /// </summary>
        public VniToken(string token = default(string), string tokenType = default(string), string scope = default(string))
        {
            Token = token;
            TokenType = tokenType;
            Scope = scope;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public string Token { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "token_type")]
        public string TokenType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scope")]
        public string Scope { get; set; }

    }
}
